### PR TITLE
Fixing issue #38 AttributeError 'NoneType' object has no attribute 'json_string'

### PR DESCRIPTION
**Pull request by cdesch**
Related issue #38 and fixes the issue of json

This PR and [PR#36](https://github.com/LeeHanYeong/django-quill-editor/pull/36) are breaking changes for Django Versions < 3.1.x

The [JSONField was introduced in Django 3.1](https://docs.djangoproject.com/en/3.1/releases/3.1/#jsonfield-for-all-supported-database-backends). django-quill-editor will have to drop support for django 3.0.x versions.

### CODE REVIEW

**Comment by cdesch** [comment]
@LeeHanYeong do you want to drop support for django 3.0.x in favor of django 3.1.x to support the `JSONField`?

**Comment by void-witch** [comment]
this was already fixed in #36, which also has the backwards-compatible version based on TextField. also, 3.0 is being dropped by django in a few months: https://www.djangoproject.com/download/#supported-versions

**Comment by cdesch** [comment]
ah, thanks @void-witch. Sounds like the way is forward!

@LeeHanYeong can we merge and increment the version of the project? I got it to work with https://github.com/LeeHanYeong/django-quill-editor-sample after updating the sample to django 3.1.x. 

Is there a better way for the sample and tests to merge into one repo?

**Comment by LeeHanYeong** [comment]
@cdesch It is better to drop support for django 3.0, which is being discontinued.
The sample repo has a lot of sample code that has nothing to do with the execution module, so it is not good to integrate it.
It would be nice to write a test related to the behavior.

**Pull request merged**
