### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by michaldyczko**
Fixes for content damage on validation error, fixtures format and null value bug.

### CODE REVIEW

**Comment by michaldyczko** [comment]
Another fix of non-saving data for dynamically created quills.

**Comment by LeeHanYeong** [comment]
Delete the logic that processes the dynamic form from `widget.html`. I haven't considered the case of creating an editor dynamically.
Existing examples were not executed in the added code. So I merged it except for that part.
An example project can be found in [django-quill-editor-sample](https://github.com/LeeHanYeong/django-quill-editor-sample).
Thanks for the contribution. I will check the dynamic form code you added later :)

**Comment by LeeHanYeong** [comment]
Your PR is merged into the master branch using a separate branch. Thank you.
[c9d2837bbf8ac79ca375ec230362417a49ee7b54](https://github.com/LeeHanYeong/django-quill-editor/commit/c9d2837bbf8ac79ca375ec230362417a49ee7b54)

**Comment by michaldyczko** [comment]
Thank you :)

**Pull request merged**
