### PR TITLE
rewrite QuillField to inherit JSONField

### LINKED ISSUE #26: [feature] make QuillField inherit JSONField
since QuillField stores text in the database directly as json-encoded text, it would be better to store it as a [JSONField](https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.JSONField). every major db backend supports the JSONField, so switching will not only be more idiomatic, but will also inform the db backend to apply any optimizations to speed up queries

~~i think the change would be pretty simple~~ after several hours of trying, i have realized it is absolutely not simple. i thought i could implement this on my own, but that is clearly not the case haha

### PR DESCRIPTION
**Pull request by void-witch**
this allows the db backend to apply any optimizations it might want/need
closes #26

checked everything out in a personal project. i can use the admin panel with a QuillField just fine, multiple edits work fine, and everything renders properly. i also checked my db (postgres) and the json getting stored is correct

### CODE REVIEW

**Comment by cobang** [comment]
Hello @void-witch, thank you for starting to implement JSON based Quill field, I also consider to use it.

As far as I see, you have only changed the form field. [DB field](https://github.com/void-witch/django-quill-editor/blob/subclass-json/django_quill/fields.py#L101) still inherited from `TextField`. Is it intended?

**Review by LeeHanYeong — APPROVED** [review]
Django supports JSONField in all db backends from version 3.x, so I think this is a good change.

**Comment by void-witch** [comment]
> Hello @void-witch, thank you for starting to implement JSON based Quill field, I also consider to use it.
> 
> As far as I see, you have only changed the form field. [DB field](https://github.com/void-witch/django-quill-editor/blob/subclass-json/django_quill/fields.py#L101) still inherited from `TextField`. Is it intended?

hmm, you're right. i wrote this a while ago so i can't be sure, but i *seem* to remember this being intended. that said, i also screwed some stuff up working with other branches recently, and had to rebase to fix it so i can't be sure. i remember having issues trying to make the model field inherit from jsonfield

i did just test it out, and the admin interface crashes. i'll figure out what that's about

**Comment by cobang** [comment]
@void-witch Thank you for your reply. It crashed on my local environment too but didn't check the problem.
I have just open another draft PR for this. You may want to review it. https://github.com/LeeHanYeong/django-quill-editor/pull/36

**Pull request merged**
